import type { AnalysisResult } from "@/types/analysis"

export const MOCK_ANALYSIS: AnalysisResult = {
  score: 62,
  subscores: {
    subscriptions: 45,
    vendors: 70,
    recurring: 60,
    concentration: 55,
    cashflow: 75,
  },
  totalExpenses: 48320.5,
  totalIncome: 67800.0,
  netResult: 19479.5,
  periodStart: new Date("2024-10-01"),
  periodEnd: new Date("2024-12-31"),
  savingsMin: 2100,
  savingsMax: 4800,
  leaks: [
    {
      id: "l1",
      type: "subscription",
      title: "Assinaturas sobrepostas de armazenamento em nuvem",
      description: "Você paga por Google Drive, Dropbox e OneDrive simultaneamente, com capacidade ociosa em todos.",
      impact: "high",
      amount: 890.0,
      category: "tecnologia",
    },
    {
      id: "l2",
      type: "duplicate",
      title: "Pagamento duplicado — Fornecedor Gráfica Total",
      description: "Detectados 2 pagamentos idênticos de R$450 em 14/11/2024 com intervalo de 3 horas.",
      impact: "high",
      amount: 450.0,
      category: "fornecedores",
    },
    {
      id: "l3",
      type: "anomaly",
      title: "Gasto atípico em Marketing Digital",
      description: "Despesa 3,2x acima da média histórica em outubro/2024. Possível fatura errada ou compra não autorizada.",
      impact: "medium",
      amount: 2300.0,
      category: "marketing",
    },
    {
      id: "l4",
      type: "concentration",
      title: "Alta concentração em único fornecedor",
      description: "42% dos custos operacionais concentrados em um único fornecedor aumenta seu risco de negociação.",
      impact: "medium",
      amount: 1200.0,
      category: "operacional",
    },
    {
      id: "l5",
      type: "subscription",
      title: "Software com plano maior que o necessário",
      description: "Plano Enterprise contratado para 50 usuários, utilização média de 12 usuários nos últimos 3 meses.",
      impact: "low",
      amount: 680.0,
      category: "tecnologia",
    },
  ],
  opportunities: [
    {
      id: "o1",
      title: "Renegociar contrato de internet corporativa",
      description: "Provedores concorrentes oferecem a mesma velocidade por até 35% menos. Seu contrato vence em 60 dias.",
      action: "Solicitar cotações com Vivo Empresas, NET e Claro e apresentar ao fornecedor atual antes do vencimento.",
      impact: "high",
      urgency: "soon",
      savingsEstimate: 650,
      category: "infraestrutura",
      difficulty: "easy",
      status: "open",
    },
    {
      id: "o2",
      title: "Consolidar ferramentas de comunicação",
      description: "Você usa Slack, Teams e WhatsApp Business. Migrar para um único hub pode economizar R$380/mês.",
      action: "Avaliar quais times usam cada ferramenta e migrar para o Slack ou Teams centralizado.",
      impact: "medium",
      urgency: "soon",
      savingsEstimate: 380,
      category: "tecnologia",
      difficulty: "medium",
      status: "open",
    },
    {
      id: "o3",
      title: "Migrar para plano anual nos softwares principais",
      description: "3 softwares que você usa oferecem desconto de 20-30% no plano anual vs mensal.",
      action: "Comparar custo anual vs mensal e antecipar renovações para aproveitar desconto.",
      impact: "medium",
      urgency: "monitor",
      savingsEstimate: 290,
      category: "tecnologia",
      difficulty: "easy",
      status: "open",
    },
  ],
  alerts: [
    {
      id: "a1",
      type: "cash_flow",
      severity: "critical",
      title: "Caixa negativo projetado para 15 de janeiro",
      message: "Com base nos pagamentos recorrentes mapeados, o saldo estimado em 15/jan é -R$3.200. Ação necessária.",
      amount: 3200,
    },
    {
      id: "a2",
      type: "duplicate",
      severity: "critical",
      title: "Pagamento duplicado detectado — confirme antes de pagar",
      message: "Fatura #2847 (R$450) aparece 2 vezes no extrato. Verifique com o fornecedor antes de qualquer novo pagamento.",
      amount: 450,
    },
    {
      id: "a3",
      type: "subscription",
      severity: "warning",
      title: "3 assinaturas vencem nos próximos 7 dias",
      message: "Adobe CC, Hotjar e Semrush renovam automaticamente. Total em risco: R$890/mês.",
      amount: 890,
    },
    {
      id: "a4",
      type: "anomaly",
      severity: "warning",
      title: "Despesa de marketing 3x acima do normal",
      message: "A despesa de outubro em tráfego pago foi de R$8.400 contra média de R$2.600. Verifique se houve aprovação.",
      amount: 8400,
    },
  ],
  actions: [
    {
      id: "ac1",
      title: "Cancelar assinatura Dropbox Business",
      description: "Você tem capacidade ociosa no Google Drive. Migrar os arquivos e cancelar o Dropbox economiza R$240/mês.",
      rationale: "Eliminação imediata de custo redundante com baixo esforço de migração.",
      impact: "high",
      urgency: "immediate",
      difficulty: "easy",
      savingsEstimate: 240,
      category: "tecnologia",
      status: "pending",
      priority: 1,
    },
    {
      id: "ac2",
      title: "Investigar e estornar pagamento duplicado",
      description: "Contactar Gráfica Total para confirmar o pagamento duplicado de R$450 e solicitar estorno ou compensação.",
      rationale: "Recuperação imediata de R$450 com uma ligação ou email.",
      impact: "high",
      urgency: "immediate",
      difficulty: "easy",
      savingsEstimate: 450,
      category: "fornecedores",
      status: "pending",
      priority: 2,
    },
    {
      id: "ac3",
      title: "Renegociar plano de internet antes do vencimento",
      description: "Solicitar 3 cotações e apresentar a menor ao fornecedor atual em até 30 dias.",
      rationale: "Contrato vence em 60 dias — janela ideal para negociar sem risco de interrupção.",
      impact: "high",
      urgency: "soon",
      difficulty: "easy",
      savingsEstimate: 650,
      category: "infraestrutura",
      status: "pending",
      priority: 3,
    },
    {
      id: "ac4",
      title: "Fazer downgrade do plano do software enterprise",
      description: "Migrar do plano Enterprise (50 usuários) para Business (20 usuários) — uso real é de 12 pessoas.",
      rationale: "Pagamento por capacidade que não é utilizada.",
      impact: "medium",
      urgency: "soon",
      difficulty: "easy",
      savingsEstimate: 680,
      category: "tecnologia",
      status: "pending",
      priority: 4,
    },
  ],
  categoryBreakdown: [
    { category: "Folha de pagamento", amount: 18500, percentage: 38, count: 3, trend: "stable" },
    { category: "Marketing", amount: 8400, percentage: 17, count: 12, trend: "up" },
    { category: "Tecnologia/SaaS", amount: 6200, percentage: 13, count: 18, trend: "up" },
    { category: "Fornecedores", amount: 5800, percentage: 12, count: 8, trend: "stable" },
    { category: "Infraestrutura", amount: 4100, percentage: 8, count: 5, trend: "down" },
    { category: "Outros", amount: 5320, percentage: 11, count: 22, trend: "stable" },
  ],
  monthlyTrend: [
    { month: "Jul/24", amount: 38200, income: 52000, expenses: 38200 },
    { month: "Ago/24", amount: 41500, income: 58000, expenses: 41500 },
    { month: "Set/24", amount: 39800, income: 60000, expenses: 39800 },
    { month: "Out/24", amount: 52100, income: 71000, expenses: 52100 },
    { month: "Nov/24", amount: 44600, income: 63000, expenses: 44600 },
    { month: "Dez/24", amount: 48320, income: 67800, expenses: 48320 },
  ],
  topVendors: [
    { vendor: "Folha / RH", amount: 18500, count: 3, percentage: 38 },
    { vendor: "Google Ads", amount: 5200, count: 4, percentage: 11 },
    { vendor: "Gráfica Total", amount: 4100, count: 6, percentage: 8, isRecurring: false },
    { vendor: "AWS", amount: 2800, count: 1, percentage: 6, isRecurring: true },
    { vendor: "Adobe Creative Cloud", amount: 1890, count: 3, percentage: 4, isRecurring: true },
    { vendor: "Aluguel", amount: 3800, count: 3, percentage: 8, isRecurring: true },
    { vendor: "Contabilidade", amount: 1500, count: 3, percentage: 3, isRecurring: true },
    { vendor: "Dropbox Business", amount: 720, count: 3, percentage: 1, isRecurring: true },
  ],
  createdAt: new Date().toISOString(),
  version: "1.0",
}

export const MOCK_SCORE_HISTORY = [
  { date: "Set/24", score: 54 },
  { date: "Out/24", score: 48 },
  { date: "Nov/24", score: 57 },
  { date: "Dez/24", score: 62 },
]
