/* ─── Category Definition ───────────────────────────────────────────────────── */
export interface Category {
  slug: string
  name: string
  icon: string
  color: string
  description: string
  keywords: string[]
}

/* ─── Categories ────────────────────────────────────────────────────────────── */
export const CATEGORIES: Category[] = [
  {
    slug: "ferramentas_software",
    name: "Ferramentas & Software",
    icon: "💻",
    color: "#3B82F6",
    description: "SaaS, assinaturas de software, ferramentas digitais",
    keywords: [
      "adobe",
      "figma",
      "slack",
      "notion",
      "asana",
      "trello",
      "jira",
      "github",
      "gitlab",
      "aws",
      "amazon web services",
      "google cloud",
      "azure",
      "heroku",
      "vercel",
      "netlify",
      "digitalocean",
      "cloudflare",
      "zapier",
      "hubspot",
      "salesforce",
      "pipedrive",
      "clickup",
      "monday.com",
      "zoom",
      "loom",
      "miro",
      "linear",
      "intercom",
      "zendesk",
      "freshdesk",
      "typeform",
      "hotjar",
      "mixpanel",
      "segment",
      "datadog",
      "sentry",
      "postman",
      "canva",
      "dropbox",
      "box.com",
      "1password",
      "lastpass",
      "bitwarden",
      "webflow",
      "squarespace",
      "wix",
      "shopify",
      "woocommerce",
      "softr",
      "airtable",
      "bubble",
      "software",
      "licenca",
      "licença",
      "subscription",
      "saas",
      "plugin",
      "extensao",
      "extensão",
      "api",
      "supabase",
      "firebase",
      "mongodb",
      "twilio",
      "sendgrid",
      "mailchimp",
      "activecampaign",
      "brevo",
      "convertkit",
      "chatgpt",
      "openai",
      "anthropic",
    ],
  },
  {
    slug: "marketing",
    name: "Marketing & Publicidade",
    icon: "📣",
    color: "#F59E0B",
    description: "Anúncios, campanhas, ferramentas de marketing",
    keywords: [
      "google ads",
      "facebook ads",
      "meta ads",
      "instagram ads",
      "tiktok ads",
      "linkedin ads",
      "twitter ads",
      "taboola",
      "outbrain",
      "influencer",
      "marketing",
      "publicidade",
      "propaganda",
      "anuncio",
      "anúncio",
      "campanha",
      "seo",
      "sem",
      "social media",
      "midia social",
      "mídia social",
      "google analytics",
      "semrush",
      "ahrefs",
      "moz",
      "rdstation",
      "rd station",
      "hubspot marketing",
      "mailchimp",
      "email marketing",
      "branding",
      "design grafico",
      "design gráfico",
      "fotografia",
      "video",
      "vídeo",
      "producao",
      "produção",
      "agencia",
      "agência",
      "freelancer",
      "copywriter",
      "content",
      "conteudo",
      "conteúdo",
    ],
  },
  {
    slug: "pessoal",
    name: "Pessoal & RH",
    icon: "👥",
    color: "#8B5CF6",
    description: "Salários, benefícios, folha de pagamento, freelancers",
    keywords: [
      "folha",
      "salario",
      "salário",
      "pagamento",
      "ferias",
      "férias",
      "13o",
      "13°",
      "decimo terceiro",
      "décimo terceiro",
      "rescisao",
      "rescisão",
      "inss",
      "fgts",
      "irrf",
      "vale transporte",
      "vale refeicao",
      "vale refeição",
      "vale alimentacao",
      "vale alimentação",
      "plano saude",
      "plano de saúde",
      "convenio medico",
      "convênio médico",
      "seguro vida",
      "seguro de vida",
      "bonus",
      "bônus",
      "comissao",
      "comissão",
      "pro labore",
      "pró-labore",
      "funcionario",
      "funcionário",
      "colaborador",
      "contratacao",
      "contratação",
      "terceirizado",
      "freelancer",
      "estagiario",
      "estagiário",
      "trainee",
      "gupy",
      "catho",
      "linkedin premium",
      "recrutamento",
      "selecao",
      "seleção",
      "rhf",
      "rh",
      "beneficios",
      "benefícios",
      "gympass",
      "totalpass",
      "wellhub",
      "clt",
      "pj",
    ],
  },
  {
    slug: "operacional",
    name: "Operacional",
    icon: "⚙️",
    color: "#06B6D4",
    description: "Equipamentos, manutenção, insumos operacionais",
    keywords: [
      "manutencao",
      "manutenção",
      "reparo",
      "conserto",
      "equipamento",
      "maquina",
      "máquina",
      "ferramenta",
      "material",
      "insumo",
      "materia prima",
      "matéria-prima",
      "estoque",
      "producao",
      "produção",
      "operacao",
      "operação",
      "limpeza",
      "higiene",
      "uniforme",
      "epi",
      "seguranca do trabalho",
      "segurança do trabalho",
      "laudo",
      "certificacao",
      "certificação",
      "licenca",
      "licença",
      "alvara",
      "alvará",
      "regularizacao",
      "regularização",
      "servicos tecnicos",
      "serviços técnicos",
      "assistencia tecnica",
      "assistência técnica",
      "suporte",
      "consultoria",
      "treinamento",
      "capacitacao",
      "capacitação",
      "curso",
    ],
  },
  {
    slug: "fornecedores",
    name: "Fornecedores",
    icon: "📦",
    color: "#10B981",
    description: "Pagamentos a fornecedores de produtos e serviços",
    keywords: [
      "fornecedor",
      "parceiro",
      "distribuidor",
      "atacado",
      "revenda",
      "mercadoria",
      "produto",
      "compra",
      "pedido",
      "nota fiscal",
      "nf",
      "nfe",
      "nf-e",
      "invoice",
      "fatura",
      "duplicata",
      "boleto fornecedor",
      "pagamento fornecedor",
      "estoque",
      "reposicao",
      "reposição",
    ],
  },
  {
    slug: "financeiro",
    name: "Financeiro & Bancário",
    icon: "🏦",
    color: "#3B82F6",
    description: "Tarifas bancárias, juros, financiamentos, IOF",
    keywords: [
      "tarifa",
      "taxa",
      "juros",
      "iof",
      "cet",
      "financiamento",
      "emprestimo",
      "empréstimo",
      "credito",
      "crédito",
      "debito",
      "débito",
      "ted",
      "doc",
      "pix taxa",
      "boleto bancario",
      "boleto bancário",
      "anuidade",
      "manutencao conta",
      "manutenção conta",
      "pacote servicos",
      "pacote serviços",
      "tarifas bancarias",
      "tarifas bancárias",
      "cheque",
      "overdraft",
      "limite",
      "conta corrente",
      "conta bancaria",
      "conta bancária",
      "banco",
      "itau",
      "bradesco",
      "santander",
      "bb",
      "banco do brasil",
      "caixa",
      "nubank",
      "inter",
      "c6",
      "btg",
      "xp",
      "stone",
      "pagseguro",
      "mercadopago",
      "asaas",
      "iugu",
      "stripe",
      "paypal",
      "adyen",
      "maquininha",
      "maquina cartao",
      "máquina cartão",
      "pos",
      "antecipacao",
      "antecipação",
      "recebivel",
      "recebível",
      "cobranca",
      "cobrança",
      "inadimplencia",
      "inadimplência",
    ],
  },
  {
    slug: "impostos",
    name: "Impostos & Tributos",
    icon: "📋",
    color: "#EF4444",
    description: "Impostos federais, estaduais, municipais e contribuições",
    keywords: [
      "imposto",
      "tributo",
      "contribuicao",
      "contribuição",
      "inss",
      "fgts",
      "irpj",
      "csll",
      "pis",
      "cofins",
      "iss",
      "icms",
      "ipi",
      "simples nacional",
      "das",
      "guia",
      "gps",
      "darf",
      "gare",
      "gnre",
      "receita federal",
      "prefeitura",
      "sefaz",
      "municipio",
      "estado",
      "federal",
      "mei",
      "cnpj",
      "parcelamento",
      "refis",
      "pert",
      "parcelamento fiscal",
      "multa fiscal",
      "juros fiscais",
      "divida ativa",
      "dívida ativa",
      "regularizacao fiscal",
      "regularização fiscal",
      "contador",
      "contabilidade",
      "escritorio contabil",
      "escritório contábil",
      "declaracao",
      "declaração",
    ],
  },
  {
    slug: "administrativo",
    name: "Administrativo",
    icon: "🗂️",
    color: "#8B8FA8",
    description: "Material de escritório, papelaria, correios, outros admin",
    keywords: [
      "material escritorio",
      "material de escritório",
      "papelaria",
      "impressao",
      "impressão",
      "impressora",
      "toner",
      "cartucho",
      "papel",
      "caneta",
      "correios",
      "sedex",
      "pac",
      "postagem",
      "envio",
      "courier",
      "despacho",
      "documentacao",
      "documentação",
      "cartorio",
      "cartório",
      "registro",
      "certidao",
      "certidão",
      "firma reconhecida",
      "telefone",
      "celular",
      "internet",
      "plano",
      "claro",
      "vivo",
      "tim",
      "oi",
      "net",
      "comgas",
      "cpfl",
      "enel",
      "light",
      "telefonia",
      "mensalidade",
      "assinatura",
      "servico",
      "serviço",
    ],
  },
  {
    slug: "instalacoes",
    name: "Instalações",
    icon: "🏢",
    color: "#F97316",
    description: "Aluguel, condomínio, energia, água, manutenção predial",
    keywords: [
      "aluguel",
      "locacao",
      "locação",
      "condominio",
      "condomínio",
      "iptu",
      "energia",
      "luz",
      "eletricidade",
      "gas",
      "gás",
      "agua",
      "água",
      "esgoto",
      "saneamento",
      "manutencao predial",
      "manutenção predial",
      "reforma",
      "obra",
      "construcao",
      "construção",
      "pintura",
      "eletricista",
      "encanador",
      "ar condicionado",
      "climatizacao",
      "climatização",
      "vigilancia",
      "vigilância",
      "seguranca",
      "segurança",
      "portaria",
      "coworking",
      "escritorio virtual",
      "escritório virtual",
      "domicilio fiscal",
      "domicílio fiscal",
      "sede",
      "imfraestruturas",
    ],
  },
  {
    slug: "logistica",
    name: "Logística & Transporte",
    icon: "🚚",
    color: "#84CC16",
    description: "Frete, transporte, combustível, veículos",
    keywords: [
      "frete",
      "transporte",
      "entrega",
      "logistica",
      "logística",
      "combustivel",
      "combustível",
      "gasolina",
      "etanol",
      "diesel",
      "abastecimento",
      "veiculo",
      "veículo",
      "carro",
      "moto",
      "caminhao",
      "caminhão",
      "van",
      "ipva",
      "seguro veicular",
      "seguro auto",
      "dpvat",
      "licenciamento",
      "seguro do carro",
      "manutencao veiculo",
      "manutenção veículo",
      "oficina",
      "mecanico",
      "mecânico",
      "taxi",
      "uber",
      "99",
      "ifood entrega",
      "rappi",
      "motoboy",
      "motofrete",
      "melhor envio",
      "frenet",
      "jadlog",
      "total express",
      "correios frete",
      "loggi",
    ],
  },
  {
    slug: "outros",
    name: "Outros",
    icon: "📌",
    color: "#4B4F6A",
    description: "Despesas diversas não categorizadas",
    keywords: [
      "diverso",
      "variado",
      "outros",
      "miscelaneo",
      "miscelâneo",
      "transferencia",
      "transferência",
      "saque",
      "deposito",
      "depósito",
      "retirada",
      "sangria",
      "suprimento",
    ],
  },
]

/* ─── Lookup Helpers ────────────────────────────────────────────────────────── */
export function getCategoryBySlug(slug: string): Category | undefined {
  return CATEGORIES.find((c) => c.slug === slug)
}

export function getCategoryName(slug: string): string {
  return getCategoryBySlug(slug)?.name ?? slug
}

export function getCategoryColor(slug: string): string {
  return getCategoryBySlug(slug)?.color ?? "#4B4F6A"
}

export function getCategoryIcon(slug: string): string {
  return getCategoryBySlug(slug)?.icon ?? "📌"
}

/* ─── Auto-categorization ───────────────────────────────────────────────────── */
/**
 * Attempts to categorize a transaction based on its description.
 * Returns the category slug or "outros" if no match found.
 */
export function categorizarTransacao(description: string): string {
  if (!description) return "outros"

  const normalized = description
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .trim()

  // Score each category by keyword matches
  let bestSlug = "outros"
  let bestScore = 0

  for (const category of CATEGORIES) {
    if (category.slug === "outros") continue

    let score = 0
    for (const keyword of category.keywords) {
      const normalizedKeyword = keyword
        .normalize("NFD")
        .replace(/[\u0300-\u036f]/g, "")
        .toLowerCase()

      if (normalized.includes(normalizedKeyword)) {
        // Longer keyword matches score higher (more specific)
        score += normalizedKeyword.length
      }
    }

    if (score > bestScore) {
      bestScore = score
      bestSlug = category.slug
    }
  }

  return bestSlug
}

/**
 * Returns the full Category object for a given transaction description.
 */
export function categorizarTransacaoFull(description: string): Category {
  const slug = categorizarTransacao(description)
  return getCategoryBySlug(slug) ?? CATEGORIES[CATEGORIES.length - 1]
}
